[LOCAL]
max_workers = 4
job_info_json_path = ./job_info.json
selected_accounts_json= selected_accouts.json

[GOOGLE]
# 対象のアカウント一覧
# https://docs.google.com/spreadsheets/d/1tc2sVX2zETRT-rEUbfulD2cTOf96tjFYHnth5nSqsDU/edit#gid=272588577
spread_sheet_id = 14OHoOhmtEgTA8U3Y0aQexUm2AtzlHQ8m44SVh0bfnwg
service_account_json = dym-indeed-checker-01.json
worksheet_name = scraiping

[CHATWORK]
room_id = 336800593
token = e0cdbbe200de056f492f42f5441cd763