server {

    listen 80;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;

        # allow only GitHub IP
        # allow 140.82.112.0/20;
        # allow 192.30.252.0/22;

        # allow your local PC
        # allow 127.0.0.1;
        # allow 192.168.0.0/16;

        # block all others
        deny all;

        proxy_pass http://jenkins:8080;
    }

    location ~ \.php$ {
        fastcgi_pass laravel_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

}