worker_processes auto;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    keepalive_requests 100000;

    upstream octane {
        server app:8000;
        keepalive 128;
    }

    server {
        listen 80 reuseport;
        server_name _;

        location / {
            proxy_pass http://octane;
            proxy_http_version 1.1;

            proxy_set_header Connection "";
            proxy_set_header Host $host;

            proxy_buffering off;
        }
    }
}