init-dev:
	cd terraform/environments/dev && terraform init

apply-dev:
	cd terraform/environments/dev && terraform apply

destroy-dev:
	cd terraform/environments/dev && terraform destroy

init-prod:
	cd terraform/environments/prod && terraform init

apply-prod:
	cd terraform/environments/prod && terraform apply