name: Local CI/CD

on:
    push:
        branches:
            - master
            - develop

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build Docker
              run: docker compose build

            - name: Run Containers
              run: |
                  docker compose down
                  docker compose up -d

            - name: Test App
              run: curl http://localhost:8080
